// GENERATED by design/branding/tools/mark_gen.py — JetBrains Mono 700
// `t.` as paths in the 64-unit mark space (baseline y=56). Do not edit
// by hand; run the generator instead.
import 'dart:ui';

Path brandMarkTPath() {
  final p = Path();
  p.moveTo(19.77, 56.00);
  p.quadraticBezierTo(14.86, 56.00, 12.08, 53.26);
  p.quadraticBezierTo(9.31, 50.53, 9.31, 45.67);
  p.lineTo(9.31, 28.73);
  p.lineTo(0.00, 28.73);
  p.lineTo(0.00, 21.67);
  p.lineTo(9.31, 21.67);
  p.lineTo(9.31, 12.00);
  p.lineTo(17.12, 12.00);
  p.lineTo(17.12, 21.67);
  p.lineTo(30.30, 21.67);
  p.lineTo(30.30, 28.73);
  p.lineTo(17.12, 28.73);
  p.lineTo(17.12, 45.67);
  p.quadraticBezierTo(17.12, 48.95, 20.31, 48.95);
  p.lineTo(29.68, 48.95);
  p.lineTo(29.68, 56.00);
  p.close();
  return p;
}

Path brandMarkPeriodPath() {
  final p = Path();
  p.moveTo(42.14, 56.62);
  p.quadraticBezierTo(39.47, 56.62, 37.89, 55.05);
  p.quadraticBezierTo(36.30, 53.48, 36.30, 50.84);
  p.quadraticBezierTo(36.30, 48.11, 37.89, 46.53);
  p.quadraticBezierTo(39.47, 44.95, 42.14, 44.95);
  p.quadraticBezierTo(44.84, 44.95, 46.41, 46.53);
  p.quadraticBezierTo(47.97, 48.11, 47.97, 50.84);
  p.quadraticBezierTo(47.97, 53.48, 46.41, 55.05);
  p.quadraticBezierTo(44.84, 56.62, 42.14, 56.62);
  p.close();
  return p;
}
