import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import '../theme/app_colors.dart';
import 'brand_mark_paths.dart';

/// The Typed brand mark — the `t.` from JetBrains Mono 700, pure paths.
/// Default surfaces use the bundled SVG; tintable variants paint the same
/// 64-unit geometry via [CustomPainter], so dark surfaces can render the
/// t in cream and the period in the warm accent.
class BrandMark extends StatelessWidget {
  final double size;
  final Color? fg;
  final Color? accent;

  const BrandMark({super.key, this.size = 18, this.fg, this.accent});

  @override
  Widget build(BuildContext context) {
    if (fg == null && accent == null) {
      return SvgPicture.asset(
        'assets/branding/typed-mark.svg',
        width: size,
        height: size,
        semanticsLabel: 'Typed logo',
      );
    }
    final c = context.colors;
    return SizedBox(
      width: size,
      height: size,
      child: CustomPaint(
        painter: _BrandMarkPainter(
          color: fg ?? c.fg,
          accentColor: accent ?? c.accent,
        ),
      ),
    );
  }
}

class _BrandMarkPainter extends CustomPainter {
  final Color color;
  final Color accentColor;

  _BrandMarkPainter({required this.color, required this.accentColor});

  // Same 64-unit geometry as assets/branding/typed-mark.svg — generated by
  // design/branding/tools/mark_gen.py into brand_mark_paths.dart. On dark
  // surfaces pass fg: cream (#F8F9FA-ish theme fg) so the t stays visible.
  @override
  void paint(Canvas canvas, Size size) {
    canvas.save();
    canvas.scale(size.width / 64, size.height / 64);
    final paint = Paint()..color = color;
    final accent = Paint()..color = accentColor;
    canvas.drawPath(brandMarkTPath(), paint);
    canvas.drawPath(brandMarkPeriodPath(), accent);
    canvas.restore();
  }

  @override
  bool shouldRepaint(covariant _BrandMarkPainter old) =>
      old.color != color || old.accentColor != accentColor;
}
